/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prueba.h"
#include <time.h>

void calculadora_prog_1(char *host, struct operandos operands)
{
	CLIENT *clnt;
	int  *result;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	int total=0;
	clock_t start=clock();

	for(int i=0;i<100000;i++){
		result = suma_1(&operands, clnt);
		if (result == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		total=total+*result;
	}

	clock_t end=clock();
	double time=(double) (end-start) / CLOCKS_PER_SEC;	

	printf("\nEl resultado de la suma es %d y el tiempo consumido han sido %f segundos.\n",total,time);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	operandos operands;

	printf("Este programa mide el tiempo consumido tras 100.000 llamadas a una función SUMA en el servidor.\n");
	
	printf("\nIntroduzca el valor del primer operando: ");
	scanf("%d", &operands.a);

	while(abs(operands.a)>9){ //Verify if the operand has only 1 digit
		printf("\nERROR, el operando solo puede tener un dígito\n");
		printf("\nIntroduzca el valor del primer operando: ");
		scanf("%d", &operands.a);
	}

	printf("\nIntroduzca el valor del segundo operando: ");
	scanf("%d", &operands.b);

	while(abs(operands.b)>9){
		printf("\nERROR, el operando solo puede tener un dígito\n");
		printf("\nIntroduzca el valor del segundo operando: ");
		scanf("%d", &operands.b);
	}

	calculadora_prog_1(host,operands);

	exit (0);
}
