/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prueba.h"


int calculadora_prog_1(char *host, int operation, struct operandos operands){
	
	CLIENT *clnt;
	int  *result;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch(operation){
		case 1:
			result = suma_1(&operands, clnt);
			if (result == (int *) NULL) {
				clnt_perror (clnt, "Call failed");
			}
			return *result;
			break;
		
		case 2:
			result = multiplicacion_1(&operands, clnt);
			if (result == (int *) NULL) {
				clnt_perror (clnt, "Call failed");
			}
			return *result;
			break;

		case 3:
			result = resta_1(&operands, clnt);
			if (result == (int *) NULL) {
				clnt_perror (clnt, "Call failed");
			}
			return *result;
			break;

		case 4:
			result = division_1(&operands, clnt);
			if (result == (int *) NULL) {
				clnt_perror (clnt, "Call failed");
			}
			return *result;
			break;

		case 5:
			result = potencia_1(&operands, clnt);
			if (result == (int *) NULL) {
				clnt_perror (clnt, "Call failed");
			}
			return *result;
			break;

		case 6:
			result = modulo_1(&operands, clnt);
			if (result == (int *) NULL) {
				clnt_perror (clnt, "Call failed");
			}
			return *result;
			break;

		default:
			break;
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) { //To verify we have called the program correctly
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	int operation;
	operandos operands;

	system("clear");
	printf("Esta calculadora es capaz de realizar las siguientes operaciones:\n");
	printf("1. SUMAR\n");
	printf("2. MULTIPLICAR\n");
	printf("3. RESTAR\n");
	printf("4. DIVIDIR\n");
	printf("5. POTENCIA\n");
	printf("6. MÓDULO\n");
	printf("Introduzca la operación que desee realizar: ");
	scanf("%d", &operation);

	while(operation<1 || operation>6){ //Verify if the operation is valid
		printf("\nERROR, seleccione un número de operación válido: ");
		scanf("%d", &operation);
	}

	printf("\nIntroduzca el valor del primer operando: ");
	scanf("%d", &operands.a);

	while(abs(operands.a)>9){ //Verify if the operand has only 1 digit
		printf("\nERROR, el operando solo puede tener un dígito\n");
		printf("\nIntroduzca el valor del primer operando: ");
		scanf("%d", &operands.a);
	}

	printf("\nIntroduzca el valor del segundo operando: ");
	scanf("%d", &operands.b);

	while(abs(operands.b)>9){
		printf("\nERROR, el operando solo puede tener un dígito\n");
		printf("\nIntroduzca el valor del segundo operando: ");
		scanf("%d", &operands.b);
	}

	int result=calculadora_prog_1(host,operation,operands);
	printf("\nEl resultado de la operación es %d\n",result);

	exit (0);
}
